version: "3"
services:
  ubuntu-os:
    build: ubuntu
    container_name: odoo-on-ubuntu
    volumes:
      - ./odoo:/odoo/odoo-server
      - ./config:/home/docker
    tty: true
    ports:
      - "80:8069"
